name: Post welcome yml file
on: 
  pull_request:
    types: [opened]
jobs:
  build:
    name: Post welcome yml build
    runs-on: ubuntu-latest
    steps:
      - run: gh pr comment $PR_URL --body "Welcome to the repo, R"
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
